apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ include "basket-api.name" . }}"
  labels:
    app: {{ include "basket-api.name" . }}
    chart: {{ include "basket-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  basket__ConnectionStrings: "{{ include "redis-name" . }}:6379"
  identity__Url: https://identity.orionproshop.store