apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webmvc.fullname" . }}-tls
spec:
  secretName: webmvc-orionproshop-store
  issuerRef:
    name: orionproshop-store
    kind: ClusterIssuer
  commonName: webmvc.orionproshop.store
  dnsNames:
    - orionproshop.store