apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "webmvc.fullname" . }}-tls
spec:
  secretName: {{ include "secret-name" . }}
  issuerRef:
    name: {{ .Values.info.tls.issuer }}
    kind: ClusterIssuer
  commonName: {{ .Values.app.ingress.entries.webmvc }}
  dnsNames:
    - {{ .Values.app.ingress.entries.webmvc }}