{{- $name := include "catalog-api.name" . -}}
{{- $cfgname := printf "%s-%s" "cfg" $name -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-api.fullname" . }}
  labels:
    {{- include "catalog-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "catalog-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "catalog-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "catalog-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 8081
              protocol: TCP
          env:
            - name: Kestrel__Endpoints__HTTP__Url
              value: "http://0.0.0.0:8080"
            - name: Kestrel__Endpoints__GRPC__Url
              value: "http://0.0.0.0:8081"
            - name: Kestrel__Endpoints__GRPC__Protocols
              value: Http2
            - name: ASPNETCORE_URLS
              value: "http://+:8081;http://+:8080"
            - name: PORT
              value: "8080"
            - name: GRPC_PORT
              value: "8081"
            - name: ConnectionStrings__PostgresPassword
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
          {{- if .Values.env.configMap }}
          {{- range .Values.env.configMap }}
            - name: {{ .name }}
              valueFrom:
                configMapKeyRef:
                  name: {{ $cfgname }}
                  key: {{ .key }}
          {{- end }}
          {{- end }}
          {{- if .Values.probe }}
          {{- if .Values.probe.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness.path }}
              port: {{ .Values.probe.liveness.port }}
            initialDelaySeconds: {{ .Values.probe.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.liveness.timeoutSeconds | default 1 }}
            failureThreshold: {{ .Values.probe.liveness.failureThreshold | default 3 }}
            successThreshold: {{ .Values.probe.liveness.successThreshold | default 1 }}
          {{- end }}
          {{- if .Values.probe.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness.path }}
              port: {{ .Values.probe.readiness.port }}
            initialDelaySeconds: {{ .Values.probe.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probe.readiness.timeoutSeconds | default 1 }}
            failureThreshold: {{ .Values.probe.readiness.failureThreshold | default 3 }}
            successThreshold: {{ .Values.probe.readiness.successThreshold | default 1 }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
