apiVersion: v1
kind: Service
metadata:
  name: {{ include "sql-data.fullname" . }}
  labels: {{- include "sql-data.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector: {{- include "sql-data.selectorLabels" . | nindent 4 }}
