{{ $name := include "identity-api.fullname" . }}
{{ $sql := include "sql-name" .}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ include "identity-api.name" . }}
    chart: {{ include "identity-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  identity__ConnectionStrings__PostgresHost: {{ $sql }}
  identity__ConnectionStrings__Default: ""
  identity__ConnectionStrings__PostgresDb: {{ .Values.info.sql.identity.db }}
  identity__ConnectionStrings__PostgresUser: {{ .Values.info.sql.identity.user }}