{{ $name := include "identity-api.fullname" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: "cfg-{{ $name }}"
  labels:
    app: {{ include "identity-api.name" . }}
    chart: {{ include "identity-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  identity__ConnectionString__PostgresHost: eshop-a-sql-data