# {{ $sqlsrv := include "sql-data.fullname" . }}

# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: "cfg-{{ include "identity-api.fullname" . }}"
#   labels:
#     {{- include "identity-api.labels" . | nindent 4 }}
# data:
#   identity_ConnectionString: "Host={{ $sqlsrv }};Database=IdentityDb;Username=postgres; Password=Pass@word;"
