# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - src/Services/Identity/Identity.API/*
      - deploy/k8s/helm/identity-api/Chart.yaml

resources:
  - repo: self

variables:
  tag: "$(Build.BuildId)"
  DockerImageName: "eshop-identity-service"
  DockerRepository: "quyenorion"
  DockerHubServiceConnection: "my-docker-hub"
  releaseName: "eshop-bb"

  # Agent VM image name
  vmImageName: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "$(DockerHubServiceConnection)"
              repository: "$(DockerRepository)/$(DockerImageName)"
              command: "buildAndPush"
              Dockerfile: "$(Build.SourcesDirectory)/src/Services/Identity/Identity.API/Dockerfile.az"
          - task: HelmDeploy@0
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'gke-multi-cluster'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: '$(Build.SourcesDirectory)/deploy/k8s/helm/identity-api'
              valueFile: '$(Build.SourcesDirectory)/deploy/k8s/helm/info.yaml'
              releaseName: '$(releaseName)'

