# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - deploy/k8s/helm/sql-data/Chart.yaml

resources:
  - repo: self

variables:
  vmImageName: ubuntu-latest

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
        - task: HelmDeploy@0
          inputs:
            connectionType: 'Kubernetes Service Connection'
            kubernetesServiceConnection: 'gke-multi-cluster'
            command: 'upgrade'
            chartType: 'FilePath'
            chartPath: '$(Build.SourcesDirectory)/deploy/k8s/helm/sql-data'
            releaseName: 'eshop-a'
