version: '3.4'

services:

  sqldata:
    environment:
      - POSTGRES_PASSWORD=Pass@word

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__Default=${ESHOP_AZURE_ORDERING_DB:-Host=sqldata;Database=IdentityDb;Username=postgres; Password=Pass@word;}
    ports:
      - "5105:80"
      - "5001:443"

  basket-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - Kestrel__Endpoints__GRPC__Url=http://0.0.0.0:81
      - Kestrel__Endpoints__GRPC__Protocols=Http2
      - PORT=80
    ports:
      - "5103:80"
      - "9103:81"

  ordering-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__HTTP__Url=http://0.0.0.0:80
      - ConnectionStrings__OrderingDb=${ESHOP_AZURE_ORDERING_DB:-Host=sqldata;Database=OrderingDb;Username=postgres; Password=Pass@word;}
      - Identity__Url=http://identity-api
      - PORT=80
    ports:
      - "5102:80"

  webshoppingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - Identity__Url=http://identity-api
      - Urls__Orders=http://ordering-api
    ports:
      - "5121:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identity-api
    ports:
      - "5100:80"

volumes:
  eshop-sqldata:
    external: false