version: '3.4'

services:

  sqldata:
    image: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile
    depends_on:
      - sqldata
