version: '3.4'

services:

  sqldata:
    environment:
      - POSTGRES_PASSWORD=Pass@word

  ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ConnectionStrings__OrderingDb=${ESHOP_AZURE_ORDERING_DB:-Host=sqldata;Database=OrderingDb;Username=postgres; Password=Pass@word;}
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  eshop-sqldata:
    external: false